### ISSUE TITLE
[Feature] 채팅 API 구현

### ISSUE THREAD

**Issue by Haewonny** [UMC-ON/ON-server#3]
### 🚀 Feature
> 채팅 api 구현

### ✅ To-Do
1차
- [x] `chat` 엔티티 생성
- [x] `chatting_room` 엔티티 생성
- [x] `special_chat` 엔티티 생성
- [x] DTO 생성
- [x] '[동행] 채팅방 목록 조회' API 구현
- [x] '채팅방 생성' API 구현
- [x] '채팅 내용 조회' API 구현
- [x] '메시지 전송' API 구현

2차
- [x] '[거래] 채팅방 목록 조회' API 구현
- [x] '[동행] 채팅 정보 조회' API 구현
- [x] '[거래] 채팅 정보 조회' API 구현
- [ ] 기존 ListDto → toList 메소드로 구현
