### ISSUE TITLE
[Refactor] 채팅 API 리팩토링

### ISSUE THREAD

**Issue by Haewonny** [UMC-ON/ON-server#76]
### ⚒️ Refactor
> 채팅 API 리팩토링

### ✅ To-Do
- [ ] list 반환하는 API paging 추가
- [ ] Dto class 분리
- [ ] 응답 `ResponseEntity` 로 통일
- [ ] 예외 처리 추가
