### ISSUE TITLE
[Refactor] 채팅 API 리팩토링

### ISSUE THREAD

**Issue by Haewonny** [UMC-ON/ON-server#77]
### ⚒️ Refactor
> 채팅 API 리팩토링

### ✅ To-Do
- [x] list 반환하는 API paging 추가
- [x] Dto class 분리 & 파일명 변경
- [x] 응답 `ResponseEntity` 로 통일
- [x] 예외 처리 추가
