### ISSUE TITLE
[Refactor] 홈 API 리팩토링

### ISSUE THREAD

**Issue by Haewonny** [UMC-ON/ON-server#78]
### ⚒️ Refactor
> 홈 API 리팩토링

### ✅ To-Do
- [x] `HomeService`의 `getCompanyBoardDto` Dto로 옮기기
- [x] 날짜 포맷팅 함수 global로 분리
- [x] 응답 `ResponseEntity` 로 통일
