### ISSUE TITLE
[Refactor] 알림 API 리팩토링

### ISSUE THREAD

**Issue by ri-naa** [UMC-ON/ON-server#79]
### ⚒️ Refactor
> 알림 API 리팩토링

### ✅ To-Do
- [x] 응답 `ResponseEntity` 로 통일
- [x] 도메인 cloumn 추가 
- [x] list 반환하는 API paging 추가
- [x] annotation 수정
- [x] enum 대문자로 수정
