### ISSUE TITLE
[Refactor] 일기 API 리팩토링

### ISSUE THREAD

**Issue by ri-naa** [UMC-ON/ON-server#80]
### ⚒️ Refactor
> 일기 API 리팩토링

### ✅ To-Do
- [x] 응답 `ResponseEntity` 로 통일
- [x] 도메인 cloumn 추가
- [x] 도메인 id, writtenDate 삭제
- [x] annotation 수정
